### ISSUE TITLE
Сравнение двух чисел не работает

### ISSUE THREAD

**Issue by wekar2k** [hexlet-basics/exercises-javascript#165]
Почему при сравнение двух цифр код не работает? Ведь в условие же написано 1 = 1 то выводить 1, я с if прописал условие, но оно не работает! И в решение учителя нету этого участка кода

```
const sumOfSeries = (startNumber, endNumber) => {
     let result = 0;

**if (startNumber === endNumber) {
     result = startNumber;
}**

for (let i = startNumber; i <= endNumber; i += 1) {
     result += i;
}

     return result;
}
```

**Comment by mokevnin** [comment]
Много неизвестных, попробуем разробраться. О каком уроке речь? Что выдавала проверка вашей функции?

p.s. Просьба оформить функцию с отступами, а то непонятно что там что.

**Comment by wekar2k** [comment]
https://ru.code-basics.com/languages/javascript/modules/loops/lessons/for

**Comment by wekar2k** [comment]
Я это учел, но ваши тесты не пускают мое решение
> Если начальное и конечное числа равны, то результатом будет то же число:

**Comment by wekar2k** [comment]
А не забудьте, понял почему не принимает
