### ISSUE TITLE
Ошибка в задаче. 

### ISSUE THREAD

**Issue by NostradamusEvel** [hexlet-basics/exercises-javascript#166]
Error: expect(received).toEqual(expected)
Expected value to equal:
  "**5678"
Received:
  "****5678"
    at /exercises-javascript/modules/40-define-functions/350-naming/test.js:8:19
    at test (/exercises-javascript/src/tests.js:27:5)
    at Object.<anonymous> (/exercises-javascript/modules/40-define-functions/350-naming/test.js:3:1)
Makefile:2: recipe for target 'test' failed
Друзья, по условию задачи должно быть четыре звездочки, но при правлильном решении условия задачи меняется. Как видите решение правильно, но условие изменилось и теперь требует две звездочки перед номером, когда я меняю в методе чтоб добавить две звездочки пишет ошибку и требует четыре. Че за???

**Comment by mokevnin** [comment]
По условию задачи количество звездочек регулируется вторым параметром. 

> когда я меняю в методе чтоб добавить две звездочки пишет ошибку и требует четыре.

Это два разных теста, посмотрите: https://github.com/hexlet-basics/exercises-javascript/blob/master/modules/40-define-functions/350-naming/test.js#L8

p.s. В конце любого урока есть ссылка на сам урок в репозитории. Там всегда можно подсмотреть как вызывается ваша функция.
