### ISSUE TITLE
Ошибка в задаче javascript 16/77

### ISSUE THREAD

**Issue by BumbleBeeJkee** [hexlet-basics/exercises-javascript#170]
Результат правильный, но другой метод через одинарные ковычки, чтобы не делать лишних экранирований.

- Did Joffrey agree?
- He did. He also said "I love using \n."
Error: expect(received).toBe(expected) // Object.is equality
Expected: "- Did Joffrey agree?
- He did. He also said /"I love using //n/"."
Received: "- Did Joffrey agree?
- He did. He also said /"I love using //n./""
Difference:
- Expected
+ Received
  - Did Joffrey agree?
- - He did. He also said "I love using /n".
+ - He did. He also said "I love using /n."
    at expectOutput (/exercises-javascript/src/tests.js:17:21)
    at Object.<anonymous> (/exercises-javascript/modules/25-strings/15-escape-characters/test.js:4:1)
Makefile:2: recipe for target 'test' failed

**Comment by mokevnin** [comment]
Честно говоря из этого вывода не понятно совсем что было и что стало. Оформите пожалуйста блоки кода как код в маркдауне.

**Comment by BumbleBeeJkee** [comment]
вчера вначале сделал этим методом
console.log('- Did Joffrey agree?\n- He did. He also said "I love using \\n".');
и он не принял мой ответ за верный, хотя консоль показала как надо.
а решение мне показало этот ответ правильным
console.log("- Did Joffrey agree?\n- He did. He also said \"I love using \\n\".");

сегодня проверил ещё раз всё норм. может я ступил. тема закрыта.
