### ISSUE TITLE
Синтаксические ошибки

### ISSUE THREAD

**Issue by sollerias** [hexlet-basics/exercises-javascript#188]
Уважаемые господа, доброго времени суток. 

Прохожу сейчас курс "Основы JavaScript" и на 5-ом уроке столкнулся со следующим.

Вы пишите:

> Вот пример кода с синтаксической ошибкой:
> 
> `console.log('Hodor'`
> Если запустить код выше, то мы увидим следующее сообщение: `SyntaxError: missing ) after argument list`. Подобные синтаксические ошибки в JavaScript относятся к разряду “SyntaxError”. Как видно, в конце приводится путь до файла и номер строчки.

Но в конце не приводится путь до файла и номер строчки. Поправьте, пожалуйста.

**Comment by mokevnin** [comment]
Ух, покопался с этим. Проблема связана с работой новой системы импортов в Node.js, видимо в ней еще есть баги.

Я добавил пометку о том что проверить можно на https://repl.it.

**Comment by sollerias** [comment]
О, интересно, а какую вы используете версию Node.js? И какую, по вашему мнению, уже можно пускать в продакжон? У нас пока v10.16.0

**Comment by mokevnin** [comment]
Нода последняя. Но там фишка именно в использовании нативной системе модулей. Ее только недавно завезли и я ее уже включил. Вот оно: https://github.com/hexlet-basics/exercises-javascript/blob/master/src/tests.js#L14
