### ISSUE TITLE
Как мы проверяем ваши решения

### ISSUE THREAD

**Issue by sollerias** [hexlet-basics/exercises-javascript#189]
Уважаемые господа, доброго времени суток.

Прохожу сейчас курс "Основы JavaScript" и на 4-ом уроке столкнулся со следующим.

В задании вы просите:

> Выведите на экран число 9780262531962.

Это задание я выполнил буквально, т.е. записал в  `console.log(9780262531962)` число.

В то же время, в решении от учителя используется вот такой синтаксис:

> `console.log('9780262531962');`

Но в моем случае я выведу на экран действительно число, а в случае решения от учителя выведется строка. 

Уточните, пожалуйста, почему в решении от учителя записывается именно такой ответ?

**Comment by mokevnin** [comment]
Это опечатка) Спасибо, правлю!

p.s. Просьба давать линк на урок, так будет проще найти где править.

**Comment by sollerias** [comment]
Спасибо, в следующий раз кину линк!
