### ISSUE TITLE
Очепятки

### ISSUE THREAD

**Issue by sollerias** [hexlet-basics/exercises-javascript#191]
Доброго времени суток!

1. Зашел в урок: https://ru.code-basics.com/languages/javascript/modules/strings/lessons/escape-characters

Там, значится, такая опечатка:

> // Мы это не изучали, но вы должны видеть правду
// Ниже код, который возвращает длину строки
'a'.length; // 1
'\n'.lenght; // 1 !!!
'\n\n'.lenght; // 2 !!!

Нужно "lenght" исправить на "length"

2. Зашел в урок: https://ru.code-basics.com/languages/javascript/modules/variables/lessons/definition

Такие, значится, опечатки:
а) 
> Сама переменная создается и наполняется данными (инициализируется) с помощью инструкция `let greeting = 'Father!'.`

Вместо "инструкция" нужно написать "инструкции"

б) 

> Для имени переменной используется любой набор допустимых символов, к которым относятся буквы английского алфавита, цифры и знак -.

"Знак -" - здесь какой-то дикий символ, похож на дефис, на гите показывает вот такую тему: 
 "знак \_-\_". Но тут должен быть знак нижнего подчеркивания: "_"

**Comment by mokevnin** [comment]
Спасибо! Все поправил. Следующий шаг отправлять пулреквесты :D

**Comment by sollerias** [comment]
О май гадбл, это слишком крейзи! 
Ну пул так пул, реквесты так реквесты, надо значит надо. :)
