### ISSUE TITLE
Уточнение логики работы кода кнопки "Следующий".

### ISSUE THREAD

**Issue by sollerias** [hexlet-basics/exercises-javascript#201]
Уважаемые господа, доброго времени суток!

Хотел бы уточнить относительно логики работы кода в курсе обучения основам JavaScript. Например, вот такой URL: [Цепочка вызовов]( https://ru.code-basics.com/languages/javascript/modules/properties/lessons/chain-of-methods
).

В правой части страницы расположен блок, где можно невозбранно кодить. В самом низу этого блока располагаются кнопки "Предыдущий", "Проверить", "Следующий".

До момента нажатия на кнопку "Проверить" и успешного прохождения тестов кнопка "Следующий" имеет серый цвет, т.е., по идее, не должна быть активной. После прохождения тестов кнопка "Следующий" меняет цвет на синий, т.е. становится активной, щелкаешь на нее и переходишь на следующий урок.

Ситуация такова: я могу нажать на кнопку "Следующий" еще до момента прохождения тестов, когда она еще имеет серый цвет, и перейти на следующий урок.

**Вопрос в следующем**: должно ли так быть? 

По идее, пока я не пройду успешно тест, усе должно быть заблоковано.

**Comment by amshkv** [comment]
Спасибо, действительно похоже на ошибку после рефакторинга, буду разбираться!

**Comment by amshkv** [comment]
Пофиксил, огромное спасибо!)

**Comment by sollerias** [comment]
Вам спасибо. Теперь работает. Danke schön!
