### ISSUE TITLE
Вопрос по решению от учителя.

### ISSUE THREAD

**Issue by sollerias** [hexlet-basics/exercises-javascript#210]
Доброго времени суток, уважаемые господа!

Хотел бы у вас уточнить, почему в данном уроке: https://ru.code-basics.com/languages/javascript/modules/logic/lessons/logical-operators

Решение от учителя имеет именно такой вид, как на картинке во вложении под номером 1:

<img width="1552" alt="Снимок экрана 2020-04-19 в 22 02 46" src="https://user-images.githubusercontent.com/25685694/79698597-50263380-828a-11ea-8656-cc5c3b7dbdb1.png">

На картинке во вложении под номером 2 указано как выглядит функция в объяснении к уроку, соответственно, свое решение (номер 3) я основывал на том, как функция определена в объяснении.

И тут я немножко запутался в том, что нужно считать за канон? Потому что сам я больше склоняюсь к определению функции, как в решении у учителя, потому как функция получилась достаточно длинной для одной строчки и, чтобы ее корректно прочитать я бы поставил фигурные скобки и return соответственно.

**Comment by sollerias** [comment]
Добавлю.

И, внезапно, в следующем уроке ([Отрицание](https://ru.code-basics.com/languages/javascript/modules/logic/lessons/logical-negation)) картина в блоке "Решение" диаметрально противоположная (см. во вложении). Запутанно. Я так полагаю, что именно длина строки в предыдущем уроке повлияла на расставление учителем фигурных скобок в функции, но это не очевидно. К сожалению, я не помню, чтобы в предыдущих уроках где-то упоминалось про такие нюансы работы с функциями, мол, длинный код, тогда ставь фигурные скобки.

<img width="1293" alt="Снимок экрана 2020-04-19 в 22 28 51" src="https://user-images.githubusercontent.com/25685694/79699100-78fbf800-828d-11ea-82e5-47a153e8404b.png">

**Comment by mokevnin** [comment]
Скобки ставились только из-за приоритета. Когда в одном выражении собираются одновременно && и ||, то скобки ставить практически обязательно. Я поправил что мог, посмотрите.

**Comment by sollerias** [comment]
> Скобки ставились только из-за приоритета. Когда в одном выражении собираются одновременно && и ||, то скобки ставить практически обязательно. Я поправил что мог, посмотрите.

Да, про круглые скобки это понятно, меня интересовали фигурные. Посмотрел, да, теперь получилось понятно и круто. Для меня такие нюансы важны, потому что важно посмотреть на то, как шаристые люди решают задачи, и взять с них пример. Спасибо!
