### ISSUE TITLE
Вопрос по решению от учителя.

### ISSUE THREAD

**Issue by sollerias** [hexlet-basics/exercises-javascript#217]
Уважаемые господа, доброго времени суток!

Пишу вам очередной вопрос политическага характера. В то время как космические корабли бороздят просторы вселенной, простой народ нуждается в ответах. 

Имеем следующие данные. 

Урок [Синтаксический сахар](https://ru.code-basics.com/languages/javascript/modules/loops/lessons/syntax-sugar)

Решение от учителя с присвоением переменных (pic1.png):
<img width="1552" alt="pic1" src="https://user-images.githubusercontent.com/25685694/80255428-294a7180-867d-11ea-8b8d-45e899d8afb7.png">

Вернемся немного в прошлое. Урок [Условия внутри тела цикла](https://ru.code-basics.com/languages/javascript/modules/loops/lessons/conditions-inside-loops)

Решение от учителя без присвоения переменных (pic2.png):
<img width="1552" alt="pic2" src="https://user-images.githubusercontent.com/25685694/80255715-cad1c300-867d-11ea-905b-efb66de75e28.png">

Все еще урок [Условия внутри тела цикла](https://ru.code-basics.com/languages/javascript/modules/loops/lessons/conditions-inside-loops), мое решение (pic3.png):
<img width="1552" alt="pic3" src="https://user-images.githubusercontent.com/25685694/80256030-58151780-867e-11ea-83cb-d74248be0027.png">

Вопрос следующий: уточните, пожалуйста, почему такая значительная разница в  объявлении и инициализации переменных в решении от учителя на pic1 и pic2? Т.е., в первом случае, для строки `str[i]`, которая состоит из 6 символов, заводится отдельная переменная `currentChar`, состоящая из 11 символов. Во втором случае ничего не заводится, просто голышиком переменная и метод в длинную строчку. Почему бы тогда не написать так, как в решении на картинке 3? Или вообще вынести в отдельные переменные, чтобы соблюдать одну концепцию в написании решений.

**Comment by mokevnin** [comment]
>  уточните, пожалуйста, почему такая значительная разница в объявлении и инициализации переменных в решении от учителя на pic1 и pic2?

Это не значительная разница, а мелочь. Подобный код пишется в реальной жизни тысячью разных способов.

> Т.е., в первом случае, для строки str[i], которая состоит из 6 символов, заводится отдельная переменная currentChar, состоящая из 11 символов. Во втором случае ничего не заводится, просто голышиком переменная и метод в длинную строчку.
> чтобы соблюдать одну концепцию в написании решений.

Так не бывает. Решения всегда

**Comment by sollerias** [comment]
Спасибо за ответ. Я предполагал, что, всё же есть некая канва в написании кода, которой должны придерживаться специалисты, дабы сам код был более унифицированным и предсказуемым, что ли. Но, наверное, эту грань я почувствую уже при прохождении профессии на ваших курсах.

**Comment by mokevnin** [comment]
Какие-то архитектурные подходы конечно есть, но вот создание переменных к этому не относится. Тут кто в лес кто по дрова. Да и в любом случае код от человека к человеку выглядит всегда по разному.
