### ISSUE TITLE
.toFixed() in Lesson 46

### ISSUE THREAD

**Issue by nobus-1967** [hexlet-basics/exercises-javascript#229]
**Lesson 46** defines the `.toFixed()` method which formats a number using fixed-point notation. This method describes as the operation with *number*, but the authors don't specify that `.toFixed()` returns *string* representing the given number.

**Comment by zhabinka** [comment]
Thanks! I completed the lesson - https://github.com/hexlet-basics/exercises-javascript/pull/241
