### ISSUE TITLE
Error for task

### ISSUE THREAD

**Issue by S1class** [hexlet-basics/exercises-javascript#230]
const one = 'Naharis';
const two = 'Mormont';
const three = 'Sand';

Отсчет символов в языке начинается с 0 а не с 1.

Поэтому 4 символа с третьей строке не существует.

Задание
Вам даны три константы с фамилиями разных людей. Составьте и выведите на экран слово из символов в таком порядке:

третий символ из первой строки
второй символ из второй строки
четвертый символ из третьей строки
пятый символ из второй строки
третий символ из второй строки

**Comment by bsv-hub** [comment]
Вышеприведённый текст задания написан для человека, а не для "языка".
Не "Отсчет символов в языке начинается с 0", а индексация составных типов языка начинается с 0. Т.е. **0** это _индекс_ **первого** элемента.

[ещё можете прочитать в этом уроке](https://ru.code-basics.com/languages/javascript/modules/variables/lessons/symbols)

**Comment by S1class** [comment]
Теперь понял.Спасибо;)
