### ISSUE TITLE
Задание 16/79. Ошибка в примере

### ISSUE THREAD

**Issue by iQwaz** [hexlet-basics/exercises-javascript#247]
Ошибка в примере:
![изображение](https://user-images.githubusercontent.com/48980893/85233729-47301a80-b411-11ea-8c55-fd0695082c71.png)
После строки 'Gregor Clegane' должна быть одна пустая строка, а у вас отображается две, хотя даже в выводе в консоли это выглядит вот так:
![изображение](https://user-images.githubusercontent.com/48980893/85233756-7fcff400-b411-11ea-95fe-a95453852426.png)

**Comment by corsicanec82** [comment]
Спасибо.
Изменения внёс, скоро обновим вывод на сайте.
