### ISSUE TITLE
javascript Определение функций 56/79

### ISSUE THREAD

**Issue by artyuhvladislav** [hexlet-basics/exercises-javascript#322]
function doesn't return correct value. It adds incorrect count symbols '*'

**Comment by AliaksandrLiubanets** [comment]
Необходимо исправить ошибки в тексте задания. Ниже исправленный текст.
Выведите на экран первую и последнюю буквы предложения, записанного в константу text, в следующем формате:

**Comment by ashikov** [comment]
Приветствую!

Александр, спасибо! Я исправил опечатку. 

Владислав, если я правильно понял ваш вопрос, функция в решении возвращает некорректные данные. Я проверил упражнение. В решении всё в порядке, отрабатывает в соответствии с тестами. Возможно вы имеете в виду какой-то конкретный кейс? Уточните, пожалуйста.

**Comment by AliaksandrLiubanets** [comment]
Я имел в виду грамматические ошибки.

**Comment by ashikov** [comment]
В этом коммите как раз были исправлены грамматические ошибки — [fix typos #339](https://github.com/hexlet-basics/exercises-javascript/pull/339/commits/8a77aeaa00860b060eb95b82e10db5dc813a8244)

Если вы видите еще ошибки, пожалуйста, укажите на них. Кстати, вы можете самостоятельно внести изменения и отправить свой pull request. У нас есть видео о том как это сделать — [Pull request в опенсорс [Хекслет]](https://www.youtube.com/watch?v=pUT3mx1ZRUM&t=37s&ab_channel=%D0%A5%D0%B5%D0%BA%D1%81%D0%BB%D0%B5%D1%82)
