### ISSUE TITLE
Определение функций 50/79

### ISSUE THREAD

**Issue by jenikslove** [hexlet-basics/exercises-javascript#324]
По тексту, чтобы был в совершенстве: Важное замечание! В задачах где нужно реализовать функцию, эту функцию вызывать не нужно. Вызывать функцию будут автоматизированные тесты, которые проверяют ее работоспособность. Пример с вызовом выше показан только для того, чтобы вы понимали как ваша !!!!!!! фукнция !!!!!!!!!!!! будет использоваться.

**Comment by ashikov** [comment]
Приветствую!

Спасибо! Fixed!
