### ISSUE TITLE
Ошибка в тесте для задачи (Урок 63)

### ISSUE THREAD

**Issue by ditanet** [hexlet-basics/exercises-javascript#385]
Неправильное решение прошло все тесты. 

// BEGIN
const isNeutralSoldier = (color, shield) => color !== 'red' && shield !== 'false'; 
// END

export default isNeutralSoldier;

**Comment by zhabinka** [comment]
@ditanet, приветствую! Так то верно, в таком решении второе значение может быть любым. НЕо в условии задачи указаны возможные цвета щитов.
