### ISSUE TITLE
Проблема при проверке символа в строке и логического ИЛИ, когда второй символ должен быть в верхнем регистре

### ISSUE THREAD

**Issue by benjburn** [hexlet-basics/exercises-javascript#405]
В задании JavaScript > Условия внутри тела цикла 74/79 (было ещё в предыдущем, но потерял)

`const countChars = (str, char) => {  
  let i = 0;  
  let count = 0;  
  while (i < str.length) {  
    if (str[i] === char || str[i] === char.toUpperCase()) {  
      count = count + 1;  
    }  
    i = i + 1;  
  }  
  return count;  
}`

Проблема в проверке функции if 
`if (str[i] === char || str[i] === char.toUpperCase())`

Проверял с помощью repl.it , проблем не возникает
![image](https://user-images.githubusercontent.com/51505949/104025984-2e3d5a00-51e7-11eb-8259-11bed6a89fda.png)

тот же самый код, с добавлением `console.log(countChars('HexlET', 'e'));`, выводи правильные значения. Просьба проверить.

**Comment by Malcom1986** [comment]
Добрый день. Я проверил, тесты в упражнении работают корректно. Попробуйте вызвать вашу функцию с другими аргументами: countChars('HexlEt', 'E'). Должно вернуться число 2, ведь в слове HexlEt две буквы е без учета регистра, а ваша функция вернет число 1
