### ISSUE TITLE
ошибка JS урок 68

### ISSUE THREAD

**Issue by LyaraNech** [hexlet-basics/exercises-javascript#410]
Не проходит тест при любом написанном коде, выдает:
 TypeError: f is not a function
    at file:///exercises-javascript/modules/48-conditionals/60-ternary-operator/test.js:4:10
    at test (file:///exercises-javascript/src/tests.js:34:5)

**Comment by Malcom1986** [comment]
Добрый день. Возможно, вы случайно удалили из упражнения строку, которая экспортирует написанную вами функцию. Попробуйте нажать кнопку "Сбросить код", эта кнопка находится под окном редактора. Нажатие кнопки сбросит упражнение в первоначальное состояние. Не забудьте скопировать свое решение, при сбросе оно удалится.  После сброса вставьте решение между маркерами begin и end и запустите проверку еще раз. Если ошибка повторится, напишите, пожалуйста, саму функцию, которая не проходит проверку
