### ISSUE TITLE
Ошибка в задании 40/79

### ISSUE THREAD

**Issue by vladmix77** [hexlet-basics/exercises-javascript#450]
Не проходит решение пишет синтаксическая ошибка.

Проверял даже с решением учителя (такое же как и у меня) не проходит решение.

**Comment by vladmix77** [comment]
SyntaxError: missing ) after argument list

**Comment by zhabinka** [comment]
А покажите решение. 
Система выстроена так, что неверное решение не может попасть в продакшен.

**Comment by vladmix77** [comment]
console.log(calculateDistanceBetweenTowns(from-to));

**Comment by vladmix77** [comment]
const distance = calculateDistanceBetweenTowns(from-to));
console.log(distance);

**Comment by vladmix77** [comment]
TypeError: param.split is not a function
    at calculateDistanceBetweenTowns (file:///exercises-javascript/src/hexlet/got.js:58:77)
    at file:///exercises-javascript/modules/35-calling-functions/200-arguments-as-expressions/index.js:8:13
    at async expectOutput (file:///exercises-javascript/src/tests.js:17:28)

**Comment by vladmix77** [comment]
захожу с андроида firefox и chrome (из полного режима и мобильного) разницы нет

**Comment by zhabinka** [comment]
Обратите внимание, что ваш пример кода отличается от решения учителя.

`const distance = calculateDistanceBetweenTowns(from-to));` – здесь разное количество открывающих и закрывающих скобок.

А вообще, дело в том, что интерпретатор воспринимает параметр `from-to` как одну переменную. Ведь `-` (дефис) –  такой же полноценный символ, как и буквы.
