### ISSUE TITLE
a mistake in the text of the task

### ISSUE THREAD

**Issue by juliawhocodes** [hexlet-basics/exercises-javascript#490]
в задании JavaScript Операторы 7/79 JavaScript: Операторы написано 
Задание
Напишите программу, которая посчитает разность между числами 6 и -81 и выведет ответ на экран.
но когда пытаешься сделать разность, ответ твой выходит неверный.  В задании должно быть указано, что это сумма, и 81 должно быть тогда без минуса 
![image](https://user-images.githubusercontent.com/61793646/125971107-ea91693c-302f-4871-81d0-c83917998182.png)

**Comment by fey** [comment]
Добрый день. 
Здесь нужно вспомнить правила математике и то, что минус на минус дает плюс.

`6 - (-81) = x`

**Comment by juliawhocodes** [comment]
аааааа, это я тупица. ясно
