### ISSUE TITLE
Ошибка в проверке результата

### ISSUE THREAD

**Issue by LilitMilante** [hexlet-basics/exercises-javascript#491]
В задании [цепочка вызовов](https://ru.code-basics.com/languages/javascript/lessons/chain-of-methods#editor) по условию требуется обработка методом `trim()`, однако, тест проходит успешно только без него (с ним тест провален)

**Comment by a1723** [comment]
![изображение](https://user-images.githubusercontent.com/56391153/126793741-19d78350-ed39-4cd1-88db-8da451b08566.png)

**Comment by Skilsar** [comment]
Проверяется  только сам результат! По заданию нужно выполнить арифметическую операцию сложения и деление, но если  просто вывести значение "Infinity", задание так же считается выполненным правильно!

**Comment by fey** [comment]
@Skilsar а вы сейчас об этом же задании говорите? https://ru.code-basics.com/languages/javascript/lessons/chain-of-methods#solution
