### ISSUE TITLE
константа или переменная?

### ISSUE THREAD

**Issue by Veshka** [hexlet-basics/exercises-javascript#525]
Добрый день. Вот нашла несоответствие.

Урок: "Математические функции JavaScript 35/79"

В задании:
Выведите на экран абсолютное значение числа, находящегося в **переменной** soldiersCount, используя функцию Math.abs().

В редакторе:
**const** soldiersCount = -2309;

**Comment by Shramkoweb** [comment]
Fixed in https://github.com/hexlet-basics/exercises-javascript/pull/526.  
Думаю можно закрывать ?
