### ISSUE TITLE
Логически неверное утверждение в тесте 

### ISSUE THREAD

**Issue by MDViktor** [hexlet-basics/exercises-javascript#658]
https://ru.code-basics.com/languages/javascript/lessons/nan
В теме NaN абзац:
    NaN - специальное значение "не число", которое обычно говорит о том, что была выполнена бессмысленная операция. Результатом любой операции, в которой участвует NaN, будет NaN.
**Суть ошибки:** 
    Результатом не любой операции с NaN будет NaN.
    Пример :
    `Nan ** 0`
    Результат :
    1

**Comment by Malcom1986** [comment]
Спасибо, поправил!
