### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by AlexStetskij** [hexlet-basics/exercises-javascript#677]
https://github.com/hexlet-basics/exercises-javascript/blob/ba8b1210a594c61f8a57316449d8c9edb07092fe/modules/30-variables/25-interpolation/description.ru.yml#L34

**Comment by ssssank** [comment]
Как именно не работает? Как эта ссылка у вас отображается? Проверяли в разных браузерах?

**Comment by AlexStetskij** [comment]
Кажется уже работает :)
