### ISSUE TITLE
Отсутствует console.log() в третьей строке, поправьте

### ISSUE THREAD

**Issue by Yura789** [hexlet-basics/exercises-javascript#685]
const name = 'Shaya';
name.length + 5; // 10
`hi, ${name.toUpperCase()}!`; // hi, SHAYA!

**Comment by kaamosdao** [comment]
Привет! Подправил, отправил пул реквест.

**Comment by acidmaksim** [comment]
@dzencot посмотри, пожалуйста

**Comment by ashikov** [comment]
Тут мы показываем значения выражений, так что вывод на экран не требуется
