### ISSUE TITLE
Можно сразу написать, как открыть консоль браузера и запустить команду

### ISSUE THREAD

**Issue by olegmaisak** [hexlet-basics/exercises-javascript#697]
В упражнении (JavaScript / Как мы проверяем ваши решения 4/72) есть такой текст:

"Кроме наших тестов, будет крайне полезно экспериментировать с кодом в **консоли браузера**. В любой ситуации, когда вы недопоняли, или хотите попробовать разные варианты использования, смело открывайте консоль и вводите туда код".

И дана ссылка: https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html

Думаю, вместо отправки по ссылке (которую скорее всего откроют и закроют), стоит просто сказать юзеру, как открыть "консоль браузера" (Ctrl + Shift + J, Cmd + Shift + J на Mac) и предложить им сразу запустить там console.log('Hello, World!'); для пробы. Если сразу попробуют, то больше шансов, что потом хотя бы вспомнят, что эта консоль существует.

**Comment by Malcom1986** [comment]
Олег, мы в курсе изучаем основы программирования. Работа с консолью в браузере уже выходит за рамки курса
