### ISSUE TITLE
Нейтральный элемент у умножения — 0

### ISSUE THREAD

**Issue by ShiinaOtMashiny** [hexlet-basics/exercises-javascript#708]
В уроке по ссылке [JavaScript: Агрегация данных (Числа)](https://code-basics.com/ru/languages/javascript/lessons/aggregation-numbers) неверно указан ответ на вопрос: Какой нейтральный элемент у операции умножения?

Указанный ответ: Нейтральный элемент у умножения — 0
Ответ с [Wiki](https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D0%B9%D1%82%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82#:~:text=%D1%81%D1%82%D0%B0%D1%82%D1%8C%D1%8E%20%C2%AB%D0%B5%D0%B4%D0%B8%D0%BD%D0%B8%D1%86%D0%B0%20(%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0)%C2%BB,%D0%BF%D0%BE%20%D0%B0%D0%BD%D0%B0%D0%BB%D0%BE%D0%B3%D0%B8%D0%B8%20%D1%81%20%D0%BE%D0%B4%D0%BD%D0%BE%D0%B8%D0%BC%D1%91%D0%BD%D0%BD%D1%8B%D0%BC%20%D1%87%D0%B8%D1%81%D0%BB%D0%BE%D0%BC.): Нейтральный элемент у умножения — 1

**Comment by fey** [comment]
Исправлено в https://github.com/hexlet-basics/exercises-javascript/commit/c13502211c29d885f409521f2acf694798da2803
