### ISSUE TITLE
Приоритет операций 10/72. Решение учителя неверное.

### ISSUE THREAD

**Issue by Ruslan707999** [hexlet-basics/exercises-javascript#710]
Решение учителя:

console.log((70 * (3 + 4)) / (8 + 2));

Задание было сделать так, чтобы (3 + 4) и (8 + 2) высчитывались в первую очередь. Но в решении учителя после (3 + 4) высчитывается 70 * 7 поскольку это заключено в дополнительные скобки. Порядок операций нарушен. В тесте идёт проверка только на конечный результат, а не на приоритет операций.

Разве ответ не console.log(70 * (3 + 4) / (8 + 2 )); ?

**Comment by ssssank** [comment]
@dzencot посмотри, пожалуйста, кажется надо немного описание задания поправить

**Comment by rizhik356** [comment]
Берусь
