### ISSUE TITLE
не работает ссылка в теории одного из упражнений

### ISSUE THREAD

**Issue by dmitriisergeevskii** [hexlet-basics/exercises-javascript#97]
в уроке javascript → Вызов функций 34/77
https://code-basics.ru/languages/javascript/modules/calling-functions/lessons/call
в абзаце про импорты и модули дается ссылка на страницу:
Не заморачивайтесь если вам не понятен смысл этого действа, подробнее о нем можно узнать из курса [введение в программирование](https://ru.hexlet.io/courses/introduction_to_programming%3CPaste%3E)

![image](https://user-images.githubusercontent.com/49035573/55263097-f880e880-5280-11e9-935f-f4612415996f.png)

**Comment by zhabinka** [comment]
На сегодня ссылка работает корректно.
