### ISSUE TITLE
Корректировка условия задачи || или её решения

### ISSUE THREAD

**Issue by annafurman** [hexlet-basics/exercises-javascript#98]
javascript → Свойства и Методы 49/77
В условии задачи написано: "...длину отрезка с 6 **_по_** 17 символа, ...".
"по 17 символ", насколько мне известно, означает включение 17-го символа в искомый отрезок. В документации к методу substring() определен следующий синтаксис:
str.substring(indexStart[, indexEnd]),
 в котором второй аргумент описан так:
"indexEnd
Необязательный. Индекс _первого_ символа, который нужно _исключить_ из возвращенной подстроки."
В решении этой задачи 17-й символ, имея индекс 16, будет исключен из подстроки, длину которой необходимо вывести на экран. Это означает, что решение "console.log(text.substring(5, 16).trim().length);"
 не является правильным исходя из условий задания.
Или я ошибаюсь???

**Comment by zhabinka** [comment]
Верно. Вторым аргументом в .substring() передаётся индекс первого исключаемого символа.
